name: AScorePro CLI (Win)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      working-directory: ./src/AScorePro
      run: dotnet restore
    - name: Test
      working-directory: ./tests/AScorePro.Tests
      run: dotnet test --verbosity normal
    - name: Build
      working-directory: ./src/AScorePro
      run: dotnet publish -c Release -r win-x64 -o AScorePro
    - name: Zip CLI
      working-directory: ./src/AScorePro
      run: Compress-Archive -Path ./AScorePro -DestinationPath ../../AScorePro.zip
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: v0.1.${{ github.run_number }}
          name: AScorePro Win CLI v0.1.${{ github.run_number }}
          files: ./AScorePro.zip
          draft: false
          prerelease: false
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
